####  APPLICATION NAME  ####
spring.application.name=racing-core
server.servlet.context-path=/motorsport

####  SERVER PORT ####
server.port=${AS_SERVER_PORT:8086}

### PROFILE ###
spring.profiles.active=@spring.profiles.active@

####  DATABASE INFO AND CREDENTIALS  ####
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:9876}/${DATABASE_NAME:racing-db}
spring.datasource.username=${DATABASE_USERNAME:theodore}
spring.datasource.password=${DATABASE_PASSWORD:theo7272}
spring.datasource.driver-class-name=org.postgresql.Driver

### LIQUIBASE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#logging configs
logging.level.root=info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%t] %c{1} - %msg%n

### SWAGGER
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.try-it-out-enabled=true

# ------------------------------
# 1) Client-credentials (for RestClient)
# ------------------------------
spring.security.oauth2.client.registration.mobility-api.provider=auth-server
spring.security.oauth2.client.registration.mobility-api.client-id=mobility-api
spring.security.oauth2.client.registration.mobility-api.client-secret=thes333crEt
spring.security.oauth2.client.registration.mobility-api.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.mobility-api.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.mobility-api.scope=INTERNAL_SERVICE
spring.security.oauth2.client.provider.auth-server.token-uri=http://localhost:9000/auth-server/oauth2/token
# ------------------------------
# 2) JWT validation (for incoming user tokens)
# ------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/auth-server

##
account.management.url=http://localhost:8085/account-management
##

#### GRPC ####
grpc.client.auth-server.address=static://localhost:9001
grpc.client.auth-server.negotiationType=plaintext
grpc.client.auth-server.enableKeepAlive=true
