####  APPLICATION NAME  ####
spring.application.name=racing-core
server.servlet.context-path=/motorsport

####  SERVER PORT ####
server.port=${SERVER_PORT:8086}

####  DATABASE INFO AND CREDENTIALS  ####
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:9876}/${DATABASE_NAME:racing-db}
spring.datasource.username=${DATABASE_USERNAME:theodore}
spring.datasource.password=${DATABASE_PASSWORD:theo7272}
spring.datasource.driver-class-name=org.postgresql.Driver

### LIQUIBASE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

### SWAGGER
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.try-it-out-enabled=true

###------------------------------
### CLIENT CREDENTIALS
###------------------------------

mobility.oauth2.resources.account-management=urn:mobility:account-management
mobility.oauth2.resources.auth-server-grpc=urn:mobility:auth-server

### ACCOUNT-MANAGEMENT SECURITY
spring.security.oauth2.client.registration.account-management.provider=auth-server
spring.security.oauth2.client.registration.account-management.client-id=mobility-api
spring.security.oauth2.client.registration.account-management.client-secret=thes333crEt
spring.security.oauth2.client.registration.account-management.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.account-management.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.account-management.scope=INTERNAL_SERVICE
### ACCOUNT-MANAGEMENT URL
account.management.service.url=http://${ACCOUNT_MANAGEMENT_URL:localhost}:8085/account-management

### GRPC CALLS TO AUTH SERVER
spring.security.oauth2.client.registration.auth-server-grpc.provider=auth-server
spring.security.oauth2.client.registration.auth-server-grpc.client-id=mobility-api
spring.security.oauth2.client.registration.auth-server-grpc.client-secret=thes333crEt
spring.security.oauth2.client.registration.auth-server-grpc.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.auth-server-grpc.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.auth-server-grpc.scope=INTERNAL_SERVICE

### OAUTH 2 CLIENT
spring.security.oauth2.client.provider.auth-server.token-uri=http://${AUTH_SERVER_URL:localhost}:9000/auth-server/oauth2/token

###------------------------------
### INCOMING JWT TOKEN VALIDATION
###------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${AUTH_SERVER_URL:localhost}:9000/auth-server
spring.security.oauth2.resourceserver.jwt.audiences[0]=urn:mobility:racing-core
spring.security.oauth2.resourceserver.jwt.audiences[1]=urn:mobility:public-api

#### GRPC ####
grpc.client.auth-server.address=static://${AUTH_SERVER_URL:localhost}:9001
grpc.client.auth-server.negotiationType=plaintext
grpc.client.auth-server.enableKeepAlive=true


### REDIS ###
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:user49}
spring.data.redis.password=${REDIS_PASSWORD:red!!spvvvvss}
# TRUE IN PROD
spring.data.redis.ssl.enabled=${REDIS_SSL:false}

spring.data.redis.timeout=${REDIS_TIMEOUT:1s}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT:1s}
spring.cache.redis.time-to-live=10m

app.cache.key-prefix=${ENVIRONMENT:dev}:${spring.application.name}

#### RABBITMQ ####

# CONNECT
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/mobility}

# RELIABILITY
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.connection-timeout=60000
spring.rabbitmq.requested-heartbeat=60

# LISTENER
spring.rabbitmq.listener.simple.prefetch=10
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=false
