#logging configs
logging.level.com.theodore.racing=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.cache=ERROR
logging.level.org.springdoc=ERROR
logging.level.io.swagger=ERROR
logging.level.com.zaxxer.hikari=WARN
logging.level.org.hibernate=WARN
logging.file.name=logs/app.log
